@startuml
actor Alice #Pink
collections DApp #Pink
collections CowriWeb3 #YellowGreen
collections Transaction #LightGreen
collections Shell #LightGreen
collections User #LightGreen
collections Token #LightGreen
collections AuctionGroup #Yellow
collections Auction #Yellow
collections Order #Yellow
collections ZeroX #YellowGreen
collections Relayer #LightBlue
collections LiquidityProvider #LightYellow
actor Bob #Blue

autonumber
Alice -> DApp: Send Bob 100 Cowri
DApp -> CowriWeb3: sendCowri(receiver, amount)
autonumber resume "<font color=blue>"
CowriWeb3 -[#blue]> AuctionGroup: "<font color=blue> Transfer.createAuctionGroup("transfer",sender,receiver,Amount)"
AuctionGroup -[#blue]> Transaction: "<font color=blue> Transaction.getTransactionShell(sender, receiver, amount)"
AuctionGroup -[#blue]> Transaction: "<font color=blue> Transaction.getEpsilonTransactionShell() returns swapShell"
AuctionGroup -[#blue]> Transaction: "<font color=blue>Transaction.getNonOverlapShell() returns nonOverlapShell"
AuctionGroup -[#blue]> Relayer: "<font color=blue>AuctionGroup.publish();"
LiquidityProvider -[#blue]>  Relayer: "<font color=blue>Relayer.getOpenOrders() returns order[]"
LiquidityProvider -[#blue]>  Order: "<font color=blue>Order.makeBid(order)"
LiquidityProvider -[#blue]>  Relayer: "<font color=blue>Order.publishBid(order)"
Relayer -[#blue]> AuctionGroup: "<font color=blue>AuctionGroup.close(auctionGroupId)"
AuctionGroup -[#blue]> Auction: "<font color=blue>Auction.close(auctionId)"
Relayer -[#blue]> AuctionGroup: "<font color=blue>AuctionGroup.decide(auctionGroupId)"
AuctionGroup -[#blue]> Auction: "<font color=blue>Auction.decide(auctionId)"
Relayer -[#blue]> AuctionGroup: "<font color=blue>AuctionGroup.createWinningOrders(auctionGroupId)"
AuctionGroup -[#blue]> Auction: "<font color=blue>Auction.createWinningOrders(auctionId)"
Auction -[#blue]> Order: "<font color=blue>new Order(winningOrder)"
AuctionGroup -[#blue]> LiquidityProvider: "<font color=blue>AuctionGroup.publish();"
LiquidityProvider -[#blue]>  Relayer: "<font color=blue>Relayer.getOpenOrders() returns order[]"
LiquidityProvider -[#blue]>  Order: "<font color=blue>Order.make(order)"
LiquidityProvider -[#blue]>  Relayer: "<font color=blue>Order.publish(order)"
CowriWeb3 -[#blue]> AuctionGroup: "<font color=blue>Transfer.takeOrders()"
AuctionGroup -[#blue]> Auction: "<font color=blue>AuctionGroup.takeOrders()"
Auction -[#blue]> Order: "<font color=blue>Auction.takeOrders()"
Order -[#blue]> Relayer: "<font color=blue>Order.take()"
CowriWeb3 -[#blue]> Bob: "<font color=Blue>sendTokens(receiever, tokenAddress, tokenAmount)"


@enduml