@startuml
class Token {
    -name: string
    -address: string
    -balance: BigNumber
    -decimals: BigNumber
    +getTokenDecimalBalance(): BigNumber
    +setTokenDecimalBalance(tokenDecimalBalance: BigNumber): void
    +getEncodedTokenData(): string
    +getName(): string
    +setName(name: string): void
    +getAddress(): string
    +setAddress(address: string): void
    +getBalance(): BigNumber
    +getBalanceAsNumber(): number
    +setBalance(balance: BigNumber): void
    +getDecimals(): BigNumber
    +setDecimals(decimals: BigNumber): void
}
class ZeroX {
    -web3: any
    -rpcSubprovider: RPCSubprovider
    -makerProviderEngine: Web3ProviderEngine
    -takerProviderEngine: Web3ProviderEngine
    -makerContractWrappers: ContractWrappers
    -networkId: number
    +swapToken(fromToken: Token, toToken: Token): Promise<string>
    +makeOrder(fromToken: Token, toToken: Token): Promise<SignedOrder>
    +takeOrder(fromToken: Token, signedOrder: SignedOrder): Promise<string>
    -initializeLiquidityProviderAccount(): void
    -initializeMakerProviderEngine(): void
    -getMakerProviderEngine(): Web3ProviderEngine
    -initializeTakerProviderEngine(): void
    -getTakerProviderEngine(): Promise<Web3ProviderEngine>
    -initializeMakerContractWrappers(): void
    -getMakerContractWrappers(): Promise<ContractWrappers>
    -generateOrder(fromToken: Token, toToken: Token): Promise<Order>
    -validateSignedOrder(signedOrder: any, fromToken: Token): Promise<void>
    -setNetworkId(networkId: number): void
    -getNetworkId(): number
    -getExchangeAddress(networkId: number): Promise<string>
    -getMakerAddress(): string
    -getTakerAddress(): Promise<any>
    -getAssetAmount(token: Token): BigNumber
    -getAssetData(token: Token): string
    -getMakerAndTakerApproval(toToken: Token, fromToken: Token): Promise<void>
    -getMakerApprovalHash(toToken: Token): Promise<void>
    -getTakerApprovalHash(fromToken: Token): Promise<void>
    -initializeRpcSubprovider(): void
    -getRpcSubprovider(): RPCSubprovider
}
@enduml